<a href="https://colab.research.google.com/github/soura1334/MLwithPython/blob/main/Matrix_in_Python_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.62364212 0.02068585 0.40411278]
 [0.34565538 0.36639512 0.95656926]
 [0.94453864 0.07493097 0.21632798]]


Creating a Matrix with random integers

In [7]:
random_int_matrix = np.random.randint(100, size=(4,5))
print(random_int_matrix)

[[51 84 66 68 92]
 [48 75 76  7 23]
 [74 23 74 96 61]
 [82 68 42 83 60]]


Matrix with all values as 1

In [9]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [12]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [13]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [15]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [17]:
a = np.random.randint(100, size=(4,5))
print(a)

[[10 31 25 31 88]
 [13 41 44 30 70]
 [34 31 25 83 54]
 [59 17  9 94 67]]


In [18]:
transpose_a = np.transpose(a)
print(transpose_a)

[[10 13 34 59]
 [31 41 31 17]
 [25 44 25  9]
 [31 30 83 94]
 [88 70 54 67]]


In [19]:
print(a.T)

[[10 13 34 59]
 [31 41 31 17]
 [25 44 25  9]
 [31 30 83 94]
 [88 70 54 67]]
