<a href="https://colab.research.google.com/github/soura1334/MLwithPython/blob/main/Matrix_in_Python_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy

In [1]:
import numpy as np

# Matrix Addition

Two matrices can be added only if they have the same shape

Creating the two matrices

In [2]:
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding 2 matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


Creating 2 matrices with random values

In [9]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [10]:
print(matrix_1)

[[3 7 4]
 [9 8 8]
 [2 5 9]]


In [11]:
print(matrix_2)

[[ 1 10  8]
 [12  3 16]
 [12 10 16]]


In [12]:
sum = np.add(matrix_1, matrix_2)

In [13]:
print(sum)

[[ 4 17 12]
 [21 11 24]
 [14 15 25]]


# Matrix Subtraction

In [14]:
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

In [17]:
print(A)

[[2 3]
 [4 5]]


In [18]:
print(B)

[[6 7]
 [8 9]]


In [15]:
diff = A - B

In [16]:
print(diff)

[[-4 -4]
 [-4 -4]]


Creating 2 matrices with random values

In [19]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [20]:
print(matrix_1)

[[2 2 8]
 [2 5 4]
 [8 5 8]]


In [21]:
print(matrix_2)

[[13  4 14]
 [ 5 14  0]
 [11 14 15]]


In [22]:
diff = np.subtract(matrix_1, matrix_2)

In [23]:
print(diff)

[[-11  -2  -6]
 [ -3  -9   4]
 [ -3  -9  -7]]


# Multiplying a Matrix by a Scalar

In [24]:
x = 5
y = np.random.randint(10, size=(4,4))
print(y)

[[3 2 9 9]
 [5 1 9 4]
 [4 2 9 8]
 [3 2 9 8]]


In [25]:
prod = np.multiply(x,y)
print(prod)

[[15 10 45 45]
 [25  5 45 20]
 [20 10 45 40]
 [15 10 45 40]]


Multiplying 2 Matrices

In [26]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [27]:
print(matrix_3)

[[0 0 2]
 [0 3 3]
 [1 4 1]]


In [28]:
print(matrix_4)

[[2 3 0 4]
 [4 0 3 1]
 [0 2 0 4]]


In [29]:
prod = np.dot(matrix_3, matrix_4)
print(prod)

[[ 0  4  0  8]
 [12  6  9 15]
 [18  5 12 12]]


In [30]:
prod.shape

(3, 4)

# Element wise Matrix Multiplication

In [37]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [38]:
print(matrix_3)

[[1 2 3]
 [1 4 4]
 [3 1 3]]


In [39]:
print(matrix_4)

[[2 3 3]
 [3 3 1]
 [3 0 0]]


In [40]:
prod = np.multiply(matrix_3, matrix_4)
print(prod)

[[ 2  6  9]
 [ 3 12  4]
 [ 9  0  0]]
