<a href="https://colab.research.google.com/github/soura1334/PyMLLibs/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

# List vs Numpy - Time taken

In [ ]:
from time import process_time

Time taken by a List

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

0.0005850569999998889


Time taken by a NP array

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time - start_time)

0.0001383790000000218


# Numpy Arrays

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating an 1 dim array

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

Creating a 2 dim array

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


# Initial Placeholders in Numpy arrays

Create a numpy array of zeroes

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create a np array of 1s

In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Create an array of a particular value

In [ ]:
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Create an identity matrix

In [ ]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create a np array with random values

In [ ]:
b = np.random.random((3,4))
print(b)

[[0.38872328 0.57687357 0.27533277 0.55474083]
 [0.81180457 0.43289402 0.22686414 0.25194057]
 [0.46893136 0.52515964 0.93038674 0.70966615]]


Random integer values array within a specific range

In [ ]:
c = np.random.randint(10,100,(3,5))
print(c)

[[20 97 11 72 14]
 [56 61 67 19 78]
 [90 77 57 76 39]]


Array of evenly spaced values -- Specifying the number of values required

In [ ]:
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


Array of evenly spaced values - Specifying the step

In [ ]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


Convert a List to a numpy array

In [ ]:
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

# Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[62 34 15 13 51]
 [80 84 14 63 47]
 [70 69 26 23 69]
 [46 64 65 27 31]
 [84 89 31 51 43]]


Array dimension

In [ ]:
print(c.shape)

(5, 5)


Number of dimensions

In [ ]:
print(c.ndim)

2


Number of elements

In [ ]:
print(c.size)

25


Checking datatype of values in the array

In [ ]:
print(c.dtype)

int64


# Mathematical Operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


[[0 9 5]
 [4 0 0]
 [0 1 9]]
[[10 12 16]
 [15 16 11]
 [10 11 15]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[10 21 21]
 [19 16 11]
 [10 12 24]]
[[-10  -3 -11]
 [-11 -16 -11]
 [-10 -10  -6]]
[[  0 108  80]
 [ 60   0   0]
 [  0  11 135]]
[[0.         0.75       0.3125    ]
 [0.26666667 0.         0.        ]
 [0.         0.09090909 0.6       ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [ ]:
print(a)
print(b)

[[8 5 5]
 [1 9 7]
 [1 5 7]]
[[13 18 17]
 [12 11 14]
 [10 16 11]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 23 22]
 [13 20 21]
 [11 21 18]]
[[ -5 -13 -12]
 [-11  -2  -7]
 [ -9 -11  -4]]
[[104  90  85]
 [ 12  99  98]
 [ 10  80  77]]
[[0.61538462 0.27777778 0.29411765]
 [0.08333333 0.81818182 0.5       ]
 [0.1        0.3125     0.63636364]]


# Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 5 5]
 [6 9 5]]
(2, 3)


Transpose of Matrix

In [ ]:
trans = np.transpose(array)
print(trans)

[[0 6]
 [5 9]
 [5 5]]


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 1 5]
 [1 5 8]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 1]
 [1 5]
 [5 8]]
(3, 2)


Reshaping an array

In [ ]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 7 1]
 [9 5 1]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 7]
 [1 9]
 [5 1]]
(3, 2)
